- id: romejko
  name: Romejko
  image: products/romejko/romejko_quart.jpg
  price: 180 €
  gallery:
  - products/romejko/romejko_face.jpg
  - products/romejko/romejko_ombre.jpg
  - products/romejko/romejko_coin.jpg
  - products/romejko/romejko_ombre2.jpg
  - products/romejko/romejko_face2.jpg
  - products/romejko/romejko_coin2.jpg
  - products/romejko/still6.png
  - products/romejko/still2.png
  - products/romejko/still3.png
  - products/romejko/still4.png
  - products/romejko/still5.png
  - products/romejko/still1.png
  description: |
    The Romejko is a chaotic glyph-based image generator. <br>
    Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br>
    Instead, its fundamentals building blocks are <strong>glyphs</strong>, 
    <strong style="
      background: linear-gradient(to right, #ef5350, #f48fb1, #7e57c2, #2196f3, #26c6da, #43a047, #eeff41, #f9a825, #ff5722);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    ">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong>
  specs:
    - Standalone VGA source
    - USB-C 5V power
    - 12 charsets
    - 7 wordsets
    - 2 feedback mode
    - 5 resolutions
    - 2 LFO
    - multifunction TAP button
    - Analog RGB mixer
    - See the manual for full feature set
  links:
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/eVa4hw4DIcQV62s4gg
  - name: Manual
    name_fr: Manuel
    url: https://sturdy-voyage-2ea.notion.site/Romejko-User-Manual-facadefcd2624f59b74485956ee67e70?pvs=4
  - name: Website
    name_fr: Site Web
    url: https://leshauts.xyz/
  tags:
  - video
  - synth
  
- id: pattes-tempo
  name: Pattes-Tempo
  description: |
    Tap-tempo meets clock divider &amp; multiplier. <br/>
    Gate length and offset on subdivisions allow dialing dynamic CV gate sequences and precise syncing.<br/><br/>
  description_fr: |
    Un tap-tempo rencontre un diviseur et multiplieur d horloge. <br/>
    Longueur de gate et decalage sur les subdivisions permet d avoir des CV dynamiques et une synchronisation precise
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output 
  - 2 see-through LEDs linked to CLK and CLK offset outputs 
  image: products/patte/patte_troisquart.png
  gallery:
  - products/patte/patte_face.png
  - products/patte/patte_feedback.png
  - products/patte/patte_feedback2.png
  price: 140 €
  links:
  - name: Manual
    name_fr: Manuel
    url:  https://local-archeology-8e0.notion.site/PattesTempo-User-Manual-e0cf838ff7f44b3fac7d215c57a958ff
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/cNi6oI9TagvG2OUeTf9oc04
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod_pattes_tempo
  tags:
  - audio
  - video
  - modular
  
- id: mosfet
  name: Mosfet
  description: |
    Basic VCA / Wave-Shaper. <br/>
    3 little Voltage Controlled Attenuator by CV jack or Potentiometer. <br/>
    whith obviously a MOSFET <br/><br/>
  description_fr: |
    VCA / wave shaper basique. <br/>
    3 petits Voltage Controlled Attenuator par jack ou potentiometre. <br/>
    Avec evidement un MOSFET <br/><br/>
  specs:
  - 3 hp
  - 3 Potentiometer atenuater
  - 3 Jack CV
  - 3 Jack In VCA out WS
  - 3 Jack Out VCA in WS
  image: products/mosfet/mosfet_.troisquartpng.png
  gallery:
  - products/mosfet/mosfet_.face.png
  - products/mosfet/mosfet_.feedback.png
  price: 70 €
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Mosfet-User-Manual-2638a11d20e980c6afececd539f7b892
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/aFa4gAd5m7ZacpufXj9oc02
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-mosfet
  tags:
  - audio
  - video
  - fx
  - modular
  
- id: eclipse
  name: Eclipse
  description: |
    Transform Light into CV. <br/>
    Controll Voltages generator. <br/><br/>
  description_fr: |
    Transforme la lumiere en CV. <br/>
    Generateur de Controll Voltage. <br/><br/>
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output 
  - 2 see-through LEDs linked to CLK and CLK offset outputs 
  image: products/eclipse/eclipse_quart.png
  gallery:
  - products/eclipse/eclipse_Face.png
  - products/eclipse/eclipse_feedback.png
  - products/eclipse/eclipse_feedback2.png
  - products/eclipse/eclipse_profil.png
  price: 90 €
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Eclipse-User-Manual-2638a11d20e9804dbf72eb957d90260e
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/dRm9AU7L26V6exC7qN9oc03
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-eclipse
  tags:
  - audio
  - video
  - fx
  - modular
  
- id: shiftreg
  name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.png
  gallery:
  - products/shiftreg/shiftreg_face.png
  - products/shiftreg/shiftreg_profil.png
  price: 100 €
  description: |
    8 bit Shift register <br/>
  description_fr: |
    registre a decalage de 8 bits. <br/>
  specs:
  - 6 hp
  - Input jack
  - Clock input jack
  - Reset input jack
  - 8* output jacks
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Shift-Reg-User-Manual-26a8a11d20e980269424e33837a8ed0d?
  - name: Pre-order
    name_fr: Précommande
    url: https://buy.stripe.com/28EfZid5m5R2gFK4eB9oc01
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-shiftReg
  tags:
  - video
  - fx
  - modular

- id: clip
  name: Clip
  image: products/clip/ClipFP.PNG
  price: 100 €
  description: |
    The Clip is a Triple - Double simple effect<br/>
    three effects, each made by two simple effects <br/>
    Which can create aesthetics breacks and strange glitchs<br/><br/>
  description_fr: |
    Le Clip est un Triple - Double simple effet <br/>
    trois effets, chacun constitues de deux effets simples <br/>
    Qui permet de creerdes cassures esthetiques et d etranges glitchs. <br/><br/>
  specs:
    - 3x inputs jacks (2 of them are normalised)
    - 3x rotary knob
    - 3x outputs jack
  links:
  - name: Manual
    name_fr: Manuel
    url:  https://local-archeology-8e0.notion.site/Clip-User-Manual-2638a11d20e98054be98c76f1dc95993?
  - name: Pre-order
    name_fr: Précommande
    url: https://buy.stripe.com/14AaEY8P6djufBG6mJ9oc00
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-clip
  tags:
  - fx
  - video
  - modular

- id: turntable
  name: Turntable maintenance
  name_fr: Réparation de platines
  image: below.png
  tags:
  - audio
  price: Contact us
  price_fr: Nous contacter
  description: |
    I repair your <strong>turntables</strong> <br>
    <strong>Vinyl turntable repair in Lyon, France</strong><br> <br>
    <em>Diagnosis, maintenance, and refurbishment for all brands</em><br>
    Information to come<br/><br/>
  description_fr: |
    Je répare vos <strong>platines</strong> <br> 
    <strong>Réparation de platines vinyles sur Lyon</strong><br> <br> 
    <em>Diagnostic, entretien et remise en état toutes marques</em><br>
    Informations à venir<br/><br/>
  links:
  - name: Mail
    url: mailto:loulc13@gmail.com

- id: about
  name: About beLow industries
  name_fr: À propos de beLow industries
  image: below.png
  price: Read more
  price_fr: Lire plus
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective 
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  description_fr: |
    <strong>beLow industries</strong> est une initiative du collectif <a href="https://below.black" target="_blank">beLow</a>
    visant à être une plate-forme pour des fabricants d'électronique indépendants.
    Les domaines d’intérêt sont liés aux domaines de la performance et de la production audiovisuelle, dans des contextes live et en studio.<br/><br/>
    Comme </strong>beLow industries</strong> est un projet collectif, il s'agit d'un espace collaboratif en ligne auquel vous pouvez contribuer <a href="https://github.com/beLow-Industries/below.industries" target="_blank">sur GitHub</a>.
    <br/>
    Les ventes, les téléchargements et les expéditions sont gérés par les créateurs eux-mêmes.
  links:
  - name: Home
    name_fr: Accueil
    url: index.html
  - name: Site
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
  - name: GitHub
    url: https://github.com/beLow-Industries/below.industries
