- name: Romejko (assembled)
  id: romejko
  image: romejko.jpg
  price: 160
  description: |
    The Romejko is a chaotic glyph-based image generator. <br> Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br> Instead, its fundamentals building blocks are <strong>glyphs</strong>, <strong class="colors">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong></p>
  links:
  - name: Buy
    url: https://leshauts.xyz/
  - name: GitHub
    url: https://leshauts.xyz/
  tags:
  - video
  - synth
- name: Pattes-Tempo
  description: |
    Tap tap tap
  image: products/patte/patte_troisquart.png
  price: 60
  tags:
  - audio
  - video
  - modular
- name: Mosfet
  image: products/mosfet/mosfet_.troisquartpng.png
  price: 90
  tags:
  - audio
  - fx
  - modular
- name: TV wall 4x adapter
  image: tvwall.jpg
  price: 50
  tags:
  - video
- name: Eclipse
  image: products/eclipse/eclipse_quart.png
  price: 120
  tags:
  - video
  - fx
  - modular
- name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.png
  price: 190
  tags:
  - video
  - fx
  - modular
- name: About beLow industries
  id: about
  image: below.png
  price: 0
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective 
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  links:
  - name: Home
    url: index.html
  - name: beLow
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
