- name: Romejko
  id: romejko
  image: products/romejko/romejko_quart.jpg
  price: 180
  gallery:
  - products/romejko/romejko_face.jpg
  - products/romejko/romejko_ombre.jpg
  - products/romejko/romejko_coin.jpg
  - products/romejko/romejko_ombre2.jpg
  - products/romejko/romejko_face2.jpg
  - products/romejko/romejko_coin2.jpg
  - products/romejko/still6.png
  - products/romejko/still2.png
  - products/romejko/still3.png
  - products/romejko/still4.png
  - products/romejko/still5.png
  - products/romejko/still1.png
  description: |
    The Romejko is a chaotic glyph-based image generator. <br>
    Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br>
    Instead, its fundamentals building blocks are <strong>glyphs</strong>, 
    <strong style="
      background: linear-gradient(to right, #ef5350, #f48fb1, #7e57c2, #2196f3, #26c6da, #43a047, #eeff41, #f9a825, #ff5722);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    ">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong></p>
  specs:
    - 12x 3-position switches
    - 8x rotary knob
    - 4 different resolutions
    - 2 LFO
    - multifunction TAP button
    - 12 charsets + 6 wordsets
    - sentence generator
    - Analog RGB mixer
    - Power via Micro USB, 5V
    - VGA output
  links:
  - name: Buy
    url: https://leshauts.xyz/
  - name: GitHub
    url: https://leshauts.xyz/
  tags:
  - video
  - synth
  
- name: Pattes-Tempo
  description: |
    Tap-tempo meets clock divider &amp; multiplier. Sync to any external source via CV or by tapping the tempo with the dedicated key.
    The configurable gate length and offset on subdivisions allow dialing very tight and dynamic CV gate sequences. <br/>
    While this was designed with live analog video performance in mind, the sync and reset inputs makes it suitable for triggering rythmical events in an audio setup.
    Works well with: LoFi Future UHG, Syntonie CBV001 / Stable
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amps; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output 
  - 2 see-through LEDs linked to CLK and CLK offset outputs 
  image: products/patte/patte_troisquart.png
  gallery:
  - products/patte/patte_face.png
  - products/patte/patte_feedback.png
  - products/patte/patte_feedback2.png
  price: 60
  links:
  - name: Manuel
    url:  https://local-archeology-8e0.notion.site/PattesTempo-User-Manual-e0cf838ff7f44b3fac7d215c57a958ff?pvs=74
  tags:
  - audio
  - video
  - modular
  
- name: Mosfet
  image: products/mosfet/mosfet_.troisquartpng.png
  gallery:
  - products/mosfet/mosfet_.face.png
  - products/mosfet/mosfet_.feedback.png
  price: 50
  tags:
  - audio
  - fx
  - modular
  
- name: Eclipse
  image: products/eclipse/eclipse_quart.png
  gallery:
  - products/eclipse/eclipse_Face.png
  - products/eclipse/eclipse_feedback.png
  - products/eclipse/eclipse_feedback2.png
  - products/eclipse/eclipse_profil.png
  price: 120
  tags:
  - video
  - fx
  - modular
- name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.png
  gallery:
  - products/shiftreg/shiftreg_face.png
  - products/shiftreg/shiftreg_profil.png
  price: 190
  links:
  - name: Manuel
    url: https://local-archeology-8e0.notion.site/Shift-Reg-User-Manual-26a8a11d20e980269424e33837a8ed0d?
  tags:
  - video
  - fx
  - modular

- name: Clip
  id: clip
  price: 160
  description: |
    The Clip is a Triple - double simple effect which can create aesthetics breacks and strange glitchs
  specs:
    - 3x rotary knob
    - 3x inputs jacks (2 of them are normalised)
    - 3x outputs jack
  links:
  - name: Manuel
    url:  https://local-archeology-8e0.notion.site/Clip-User-Manual-2638a11d20e98054be98c76f1dc95993?
  tags:
  - fx
  - video
  - modular

- name: Turntable maintenance
  image: below.png
  tags:
  - audio
  price: 10000
  description: |
    Je répare vos <strong>platines</strong> mdr <br> 
    <strong>Réparation de platines vinyles sur Lyon</strong><br> <br> 
    <em>Diagnostic, entretien et remise en état toutes marques</em><br> 
    <strong>Contact :</strong> 06 00 00 00 00
  links:
  - name: Home
    url: https://google.com
  - name: Mail
    url: mailto:loulc13@gmail.com

- name: About beLow industries
  id: about
  image: below.png
  price: 0
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective 
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  links:
  - name: Home
    url: index.html
  - name: beLow
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
  - name: GitHub
    url: https://github.com/beLow-Industries/below.industries
