- id: romejko
  name: Romejko
  image: products/romejko/romejko_quart.jpg
  price: 180 €
  gallery:
  - products/romejko/romejko_face.jpg
  - products/romejko/romejko_ombre.jpg
  - products/romejko/romejko_coin.jpg
  - products/romejko/romejko_ombre2.jpg
  - products/romejko/romejko_face2.jpg
  - products/romejko/romejko_coin2.jpg
  - products/romejko/still6.jpg
  - products/romejko/still2.jpg
  - products/romejko/still3.jpg
  - products/romejko/still4.jpg
  - products/romejko/still5.jpg
  - products/romejko/still1.jpg
  description: |
    The Romejko is a chaotic glyph-based image generator. <br>
    Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br>
    Instead, its fundamentals building blocks are <strong>glyphs</strong>,
    <strong style="
      background: linear-gradient(to right, #ef5350, #f48fb1, #7e57c2, #2196f3, #26c6da, #43a047, #eeff41, #f9a825, #ff5722);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    ">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong>
  description_fr: |
    Le Romejko est un générateur autonome d’images chaotiques basé sur les glyphes. <br>
    Contrairement aux synthétiseurs vidéo, il n'est pas composé d'oscillateurs, d'encodeurs ou de mélangeurs. <br><br>
    Fondamentalement, il utilise <strong>glyphes</strong>,
    les <strong style="
      background: linear-gradient(to right, #ef5350, #f48fb1, #7e57c2, #2196f3, #26c6da, #43a047, #eeff41, #f9a825, #ff5722);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    ">couleurs</strong> et le <strong>c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹ contrôlé</strong> pour générer un flux vidéo VGA.
  specs:
    - Standalone VGA source
    - USB-C 5V power
    - 256 characters
    - 12 charsets
    - 7 wordsets
    - 2 feedback mode
    - 5 resolutions
    - 2 LFO
    - Sentence generator (458.031 combinations)
    - multifunction TAP button
    - Analog RGB mixer
    - See the manual for full feature set
  specs_fr:
    - Source VGA autonome
    - Alimentation USB-C 5V
    - 256 caractères
    - 12 jeux de caractères
    - 7 dictionnaires de mots
    - 2 modes de feedback
    - 5 résolutions
    - 2 LFO
    - Générateur de phrase (458.031 combinaisons)
    - Bouton TAP multifonction
    - Mixeur RGB analogique
    - Voir le manuel pour la liste complète des fonctionnalités
  links:
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/3cI6oG4fZeREgbZdtC4Rq03
  - name: Manual
    name_fr: Manuel
    url: https://sturdy-voyage-2ea.notion.site/Romejko-User-Manual-facadefcd2624f59b74485956ee67e70?pvs=4
  - name: Website
    name_fr: Site Web
    url: https://leshauts.xyz/
  tags:
  - video
  - synth

- id: pattes-tempo
  name: Pattes-Tempo
  description: |
    Tap-tempo meets clock divider &amp; multiplier. <br/>
    Gate length and offset on subdivisions allow dialing dynamic CV gate sequences and precise syncing.<br/><br/>
  description_fr: |
    Un tap-tempo rencontre un diviseur et multiplieur d'horloge. <br/>
    Longueur de gate et décalage sur les subdivisions permet d'avoir des CV dynamiques et une synchronisation précise.
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output
  - 2 see-through LEDs linked to CLK and CLK offset outputs
  image: products/patte/patte_troisquart.jpg
  gallery:
  - products/patte/patte_face.jpg
  - products/patte/patte_feedback.jpg
  - products/patte/patte_feedback2.jpg
  price: 140 €
  links:
  - name: Manual
    name_fr: Manuel
    url:  https://local-archeology-8e0.notion.site/PattesTempo-User-Manual-e0cf838ff7f44b3fac7d215c57a958ff
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/cNi6oI9TagvG2OUeTf9oc04
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod_pattes_tempo
  tags:
  - audio
  - video
  - modular

- id: mosfet
  name: Mosfet
  description: |
    Basic VCA / Wave-Shaper. <br/>
    3 little Voltage Controlled Attenuator by CV jack or potentiometer. <br/>
    Powered by MOSFET, obviously. <br/><br/>
  description_fr: |
    VCA / Wave-Shaper basique. <br/>
    3 petits Voltage Controlled Attenuator par jack ou potentiomètre. <br/>
    Fonctionne avec des MOSFET, évidemment. <br/><br/>
  specs:
  - 3 hp
  - 3 Potentiometer atenuater
  - 3 Jack CV
  - 3 Jack In VCA out WS
  - 3 Jack Out VCA in WS
  image: products/mosfet/mosfet_.troisquartpng.jpg
  gallery:
  - products/mosfet/mosfet_.face.jpg
  - products/mosfet/mosfet_.feedback.jpg
  price: 70 €
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Mosfet-User-Manual-2638a11d20e980c6afececd539f7b892
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/aFa4gAd5m7ZacpufXj9oc02
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-mosfet
  tags:
  - audio
  - video
  - fx
  - modular

- id: eclipse
  name: Eclipse
  description: |
    Transform light into CV. <br/>
  description_fr: |
    Transforme la lumière en CV. <br/>
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output
  - 2 see-through LEDs linked to CLK and CLK offset outputs
  image: products/eclipse/eclipse_quart.jpg
  gallery:
  - products/eclipse/eclipse_Face.jpg
  - products/eclipse/eclipse_feedback.jpg
  - products/eclipse/eclipse_feedback2.jpg
  - products/eclipse/eclipse_profil.jpg
  price: 90 €
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Eclipse-User-Manual-2638a11d20e9804dbf72eb957d90260e
  - name: Buy
    name_fr: Acheter
    url: https://buy.stripe.com/dRm9AU7L26V6exC7qN9oc03
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-eclipse
  tags:
  - audio
  - video
  - fx
  - modular

- id: shiftreg
  name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.jpg
  gallery:
  - products/shiftreg/shiftreg_face.jpg
  - products/shiftreg/shiftreg_profil.jpg
  price: 100 €
  description: |
    8-bit shift register. <br/>
  description_fr: |
    Registre à décalage de 8 bits. <br/>
  specs:
  - 6 hp
  - Input jack
  - Clock input jack
  - Reset input jack
  - 8x output jacks
  links:
  - name: Manual
    name_fr: Manuel
    url: https://local-archeology-8e0.notion.site/Shift-Reg-User-Manual-26a8a11d20e980269424e33837a8ed0d?
  - name: Pre-order
    name_fr: Précommande
    url: https://buy.stripe.com/28EfZid5m5R2gFK4eB9oc01
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-shiftReg
  tags:
  - video
  - fx
  - modular

- id: clip
  name: Clip
  image: products/clip/ClipFP.PNG
  price: 100 €
  description: |
    Clip is a triple - double basic effect.<br/>
    Three couples of effects in series which can create aesthetics breaks and strange glitchs on video signals.<br/><br/>
  description_fr: |
    Le Clip est un triple - double effet simpliste. <br/>
    Trois paires d'effets qui permettent de créer des cassures esthétiques et d'étranges glitchs sur les signaux vidéo. <br/><br/>
  specs:
    - 3x inputs jacks (2 of them are normalised)
    - 6x rotary knob
    - 3x outputs jack
  specs_fr:
    - 3x entrées jacks (2 normalisées)
    - 6x potentiomètres
    - 3x jack de sortie
  links:
  - name: Manual
    name_fr: Manuel
    url:  https://local-archeology-8e0.notion.site/Clip-User-Manual-2638a11d20e98054be98c76f1dc95993?
  - name: Pre-order
    name_fr: Précommande
    url: https://buy.stripe.com/14AaEY8P6djufBG6mJ9oc00
  - name: Contact
    url: mailto:guihery.albert@gmail.com
  - name: Git
    url: https://github.com/beLow-Industries/mod-clip
  tags:
  - fx
  - video
  - modular

- id: turntable
  name: Turntable maintenance
  name_fr: Réparation de platines vinyle
  image: products/turntable/turntable.jpg
  tags:
  - audio
  price: Contact us
  price_fr: Nous contacter
  show_price_on_product_page: false
  description: |
    Turntable servicing and repair — depends on the model<br/><br/>
    <strong>Available in Lyon, France, pick-up
    and drop-off possible.</strong><br/><br/>
    Contact by email for more information.<br/><br/>
  description_fr: |
    Révision et réparation de platine vinyle, dépend du model<br/><br/>
    <strong>Disponible sur Lyon, récupération et dépose
    possible.</strong><br/><br/>
    Contacter par mail pour plus d'information<br/><br/>
  links:
  - name: Mail
    url: mailto:maloucarree@gmail.com

- id: about
  name: About beLow
  name_fr: À propos de beLow
  image: below.jpg
  price: Read more
  price_fr: Lire plus
  show_price_on_product_page: false
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  description_fr: |
    <strong>beLow industries</strong> est une initiative du collectif <a href="https://below.black" target="_blank">beLow</a>
    visant à être une plate-forme pour des fabricants d'électronique indépendants.
    Les domaines d’intérêt sont liés aux domaines de la performance et de la production audiovisuelle, dans des contextes live et en studio.<br/><br/>
    Comme </strong>beLow industries</strong> est un projet collectif, il s'agit d'un espace collaboratif en ligne auquel vous pouvez contribuer <a href="https://github.com/beLow-Industries/below.industries" target="_blank">sur GitHub</a>.
    <br/>
    Les ventes, les téléchargements et les expéditions sont gérés par les créateurs eux-mêmes.
  links:
  - name: Home
    name_fr: Accueil
    url: index.html
  - name: Site
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
  - name: GitHub
    url: https://github.com/beLow-Industries/below.industries
