- name: Romejko (assembled)
  id: romejko
  image: romejko.jpg
  price: 160
  description: |
    The Romejko is a chaotic glyph-based image generator. <br> Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br> Instead, its fundamentals building blocks are <strong>glyphs</strong>, <strong class="colors">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong></p>
  specs:
    - 12x 3-position switches
    - 8x rotary knob
    - 4 different resolutions
    - 2 LFO
    - multifunction TAP button
    - 12 charsets + 6 wordsets
    - sentence generator
    - Analog RGB mixer
    - Power via Micro USB, 5V
    - VGA output

  links:
  - name: Buy
    url: https://leshauts.xyz/
  - name: GitHub
    url: https://leshauts.xyz/
  tags:
  - video
  - synth
- name: Pattes-Tempo
  description: |
    Tap tap tap
  image: products/patte/patte_troisquart.png
  gallery:
  - products/patte/patte_face.png
  - products/patte/patte_feedback.png
  - products/patte/patte_feedback2.png
  price: 60
  tags:
  - audio
  - video
  - modular
- name: Mosfet
  image: products/mosfet/mosfet_.troisquartpng.png
  gallery:
  - products/mosfet/mosfet_.face.png
  - products/mosfet/mosfet_.feedback.png
  price: 90
  tags:
  - audio
  - fx
  - modular
- name: Eclipse
  image: products/eclipse/eclipse_quart.png
  gallery:
  - products/eclipse/eclipse_Face.png
  - products/eclipse/eclipse_feedback.png
  - products/eclipse/eclipse_feedback2.png
  - products/eclipse/eclipse_profil.png
  price: 120
  tags:
  - video
  - fx
  - modular
- name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.png
  gallery:
  - products/shiftreg/shiftreg_face.png
  - products/shiftreg/shiftreg_profil.png
  price: 190
  tags:
  - video
  - fx
  - modular


  
- name: Turntable maintenance
  image: below.png
  tags:
  - audio
  price: 10000
  description: |
    Je répare vos <strong>platines</strong> mdr
    <strong>Réparation de platines vinyles sur Lyon</strong><br>
    <em>Diagnostic, entretien et remise en état toutes marques</em><br>
    <strong>Contact :</strong> 06 00 00 00 00
  links:
  - name: Home
    url: https://google.com
  - name: Mail
    url: mailto:loulc13@gmail.com
  
  
- name: About beLow industries
  id: about
  image: below.png
  price: 0
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective 
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  links:
  - name: Home
    url: index.html
  - name: beLow
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
  - name: GitHub
    url: https://github.com/beLow-Industries/below.industries
