- name: Romejko
  id: romejko
  image: products/romejko/romejko_quart.jpg
  price: 180
  gallery:
  - products/romejko/romejko_face.jpg
  - products/romejko/romejko_ombre.jpg
  - products/romejko/romejko_coin.jpg
  - products/romejko/romejko_ombre2.jpg
  - products/romejko/romejko_face2.jpg
  - products/romejko/romejko_coin2.jpg
  - products/romejko/still6.png
  - products/romejko/still2.png
  - products/romejko/still3.png
  - products/romejko/still4.png
  - products/romejko/still5.png
  - products/romejko/still1.png
  description: |
    The Romejko is a chaotic glyph-based image generator. <br>
    Unlike video synthesizers, it doesn’t rely on oscillators, encoders, or mixers. <br><br>
    Instead, its fundamentals building blocks are <strong>glyphs</strong>, 
    <strong style="
      background: linear-gradient(to right, #ef5350, #f48fb1, #7e57c2, #2196f3, #26c6da, #43a047, #eeff41, #f9a825, #ff5722);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    ">colors</strong>, and <strong>controlled c̷̛͉h̴̯̿̊ă̶̗͛ọ̷̯͊̈́ŝ̴̹</strong>
  specs:
    - Standalone VGA source
    - USB-C 5V power
    - 12 charsets
    - 7 wordsets
    - 2 feedback mode
    - 5 resolutions
    - 2 LFO
    - multifunction TAP button
    - Analog RGB mixer
    - See the manual for full feature set
  links:
  - name: Buy
    url: https://buy.stripe.com/eVa4hw4DIcQV62s4gg
  - name: Manual
    url: https://sturdy-voyage-2ea.notion.site/Romejko-User-Manual-facadefcd2624f59b74485956ee67e70?pvs=4
  - name: Website
    url: https://leshauts.xyz/
  tags:
  - video
  - synth
  
- name: Pattes-Tempo
  description: |
    Tap-tempo meets clock divider &amp; multiplier. <br/>
    Gate length and offset on subdivisions allow dialing dynamic CV gate sequences and precise syncing.<br/><br/>
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output 
  - 2 see-through LEDs linked to CLK and CLK offset outputs 
  image: products/patte/patte_troisquart.png
  gallery:
  - products/patte/patte_face.png
  - products/patte/patte_feedback.png
  - products/patte/patte_feedback2.png
  price: 140
  links:
  - name: Manuel
    url:  https://local-archeology-8e0.notion.site/PattesTempo-User-Manual-e0cf838ff7f44b3fac7d215c57a958ff
  tags:
  - audio
  - video
  - modular
  
- name: Mosfet
  description: |
    Basic VCA / Wave-Shaper. <br/>
    3 litle voltage followers by CV jack or Potentiometer.<br/><br/>
  specs:
  - 4 hp
  - 3*
  -   Potentiometer atenuater
  -   Jack CV
  -   Jack In VCA out WS
  -   Jack Out VCA in WS
  image: products/mosfet/mosfet_.troisquartpng.png
  gallery:
  - products/mosfet/mosfet_.face.png
  - products/mosfet/mosfet_.feedback.png
  price: 75
  links:
  - name: Manuel
    url: https://local-archeology-8e0.notion.site/Mosfet-User-Manual-2638a11d20e980c6afececd539f7b892
  tags:
  - audio
  - fx
  - modular
  
- name: Eclipse
  description: |
    Transform Light into CV. <br/>
    Controll Voltages generator.<br/><br/>
  specs:
  - 6 hp
  - Tap tempo keyswitch
  - SYNC &amp; RESET CV inputs
  - CLK, /2, /4, /8 dual gate output with offset control
  - /16, /3, x2 and x4 gate output 
  - 2 see-through LEDs linked to CLK and CLK offset outputs 
  image: products/eclipse/eclipse_quart.png
  gallery:
  - products/eclipse/eclipse_Face.png
  - products/eclipse/eclipse_feedback.png
  - products/eclipse/eclipse_feedback2.png
  - products/eclipse/eclipse_profil.png
  price: 75
  - name: Manuel
    url: https://local-archeology-8e0.notion.site/Eclipse-User-Manual-2638a11d20e9804dbf72eb957d90260e
  tags:
  - video
  - fx
  - modular
  
- name: ShiftReg
  image: products/shiftreg/shiftreg_troisquart.png
  gallery:
  - products/shiftreg/shiftreg_face.png
  - products/shiftreg/shiftreg_profil.png
  price: 100
  description: |
    Shift register <br/>
  specs:
  - 6 hp
  - Input jack
  - Clock input jack
  - Reset input jack
  - 8* output jacks
  image: products/eclipse/eclipse_quart.png
  links:
  - name: Manuel
    url: https://local-archeology-8e0.notion.site/Shift-Reg-User-Manual-26a8a11d20e980269424e33837a8ed0d?
  tags:
  - video
  - fx
  - modular

- name: Clip
  image: below.png
  id: clip
  price: 100
  description: |
    The Clip is a Triple - Double simple effect<br/>
    Which can create aesthetics breacks and strange glitchs<br/><br/>
  specs:
    - 3x inputs jacks (2 of them are normalised)
    - 3x rotary knob
    - 3x outputs jack
  links:
  - name: Manuel
    url:  https://local-archeology-8e0.notion.site/Clip-User-Manual-2638a11d20e98054be98c76f1dc95993?
  tags:
  - fx
  - video
  - modular

- name: Turntable maintenance
  image: below.png
  tags:
  - audio
  price: 10000
  description: |
    Je répare vos <strong>platines</strong> mdr <br> 
    <strong>Réparation de platines vinyles sur Lyon</strong><br> <br> 
    <em>Diagnostic, entretien et remise en état toutes marques</em><br> 
    <strong>Contact :</strong> 06 00 00 00 00
  links:
  - name: Home
    url: https://google.com
  - name: Mail
    url: mailto:loulc13@gmail.com

- name: About beLow industries
  id: about
  image: below.png
  price: 0
  tags:
  - about
  description: |
    <strong>beLow industries</strong> is an initiative of the <a href="https://below.black" target="_blank">beLow</a> collective 
    aimed at being a platform for independant electronics manufacturers.
    Areas of interest are linked to the fields of A/V performance and production, in both live and studio contexts.<br/><br/>
    As </strong>beLow industries</strong> is a collective project, it acts a collaborative online space that you can contribute to <a href="https://github.com/beLow-Industries/below.industries" target="_blank">on GitHub</a>.
    <br/>
    Sales, downloads and shipments are handled by creators themselves.
  links:
  - name: Home
    url: index.html
  - name: beLow
    url: https://below.black/
  - name: ig
    url: https://instagram.com/below.industries
  - name: GitHub
    url: https://github.com/beLow-Industries/below.industries
